### PR TITLE
cross browser, highlighting at-risk students and popup config window

### PR DESCRIPTION
**Pull request by jnmwangi**
Features:-
- Enable cross-browser capability using [WebExtension browser API Polyfill](https://github.com/mozilla/webextension-polyfill?tab=readme-ov-file#installation)
- Highlighting students at risk in the people page
- A popup window for setting configurations in local storage

### CODE REVIEW

**Comment by karusamuel** [comment]
Breaking changes 
- This version fails to work on Mozilla (still testing )
- Modify the @ risk student script to work on all sections currently only works with a specific [602]

**Comment by jnmwangi** [comment]
Regarding this issue:-
- This version fails to work on Mozilla (still testing )

The following is the error that is logged on installation

```
addons.xpi-utils	WARN	Add-on undefined is not correctly signed.
addons.xpi	WARN	Invalid XPI: Error: Cannot find id for addon
```

Coursed by missing the addon id and failure to sign the package.

Is it possible you build from your end as you did for version 1.3

**Comment by karusamuel** [comment]
the above error is because you were using manifest v3 which requires a pre-generated id from Mozilla switching it to v2 works 

QQ does v2 not work on google Crome?

**Comment by karusamuel** [comment]
Changing it to manifest v2 makes it work on Firefox the only pending issues are:
-  hardcode course id
- didn't see the configuration pop up on install (not sure how to get it)

**Comment by karusamuel** [comment]
Found the issue v2 does not support  pop-ups  let me update  to v3  and get back to you

**Comment by jnmwangi** [comment]
I managed to sort the hand coded course id issue

**Comment by karusamuel** [comment]
@njmwasmoringa @njmwas 
I updated the manifest to V3 and added an ID you can pull to get the changes.... a few issues I noticed:

- the flagging of at-risk students doesn't work until you click the popup (not sure if this is the expected behavior)
- updating the configuration  on the popup does not automatically  change the currently flagged students you have to reload the page 

great work on the at-risk code that's some heavy thinking there   :partying_face:  :partying_face:

**Pull request closed without merging**
